### ISSUE TITLE
提一个小小的想法

### ISSUE THREAD

**Issue by GOOD-AN** [ghosx/tieba#12]
有一个小小的想法，要不要加一个Server酱的推送，这样也方便查看签到是否成功。

**Comment by ghosx** [comment]
![image](https://user-images.githubusercontent.com/16274355/104603925-dd7ea300-56b7-11eb-8ed3-f936757af7bd.png)

可以自行接入哈，readme里面也可以看

**Comment by GOOD-AN** [comment]
好的，谢谢。
